---
# Create kafka user and group
- group: name=kafka system=yes
- user: name=kafka group=kafka system=yes

- name: "Create kafka directories"
  file: path={{ item }} state=directory mode=0755 owner=kafka group=kafka
  with_items:
    - "{{ kafka_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

# Download and install archive
- name: "Download kafka binary package archive"
  get_url:
    url:  "{{ kafka_url }}"
    dest: "/home/kafka/{{ kafka_filename }}"

- name: "Extract kafka archive"
  unarchive:
    src:  "/home/kafka/{{ kafka_filename }}"
    dest: "{{ kafka_dir }}"
    extra_opts: ['--strip-components=1']
    remote_src: yes
    creates: "{{ kafka_dir }}/bin"
    owner: kafka
    group: kafka

# Prepare service for systemd
- name: "Add environment settings for the service"
  template: src=etc_default.j2 dest=/etc/default/kafka
  when: ansible_service_mgr == 'systemd'
  notify:
    - restart kafka

- name: "Create systemd config"
  template: src=kafka.service.j2 dest=/lib/systemd/system/kafka.service
  when: ansible_service_mgr == 'systemd'
  notify:
    - reload systemctl daemon
    - restart kafka

# Add to profile.d
- name: Add kafka's bin dir to the PATH
  template:
    src: kafka_path.sh.j2
    dest: /etc/profile.d/kafka_path.sh
    mode: 0644
  when: kafka_register_path_env
